<x-app-layout title="Edit Purchase Order">
    <x-page-header title="Edit {{ $purchaseOrder->po_number }}" description="Update procurement details and the current order status." :breadcrumbs="[['label' => 'Purchase Orders', 'url' => route('procurement.index')], ['label' => $purchaseOrder->po_number, 'url' => route('procurement.show', $purchaseOrder)], ['label' => 'Edit']]">
        <x-slot name="actions"><a href="{{ route('procurement.show', $purchaseOrder) }}" class="btn btn-secondary"><i data-lucide="arrow-left" class="h-4 w-4"></i> Back to Purchase Order</a></x-slot>
    </x-page-header>
    <form method="POST" action="{{ route('procurement.update', $purchaseOrder) }}">@csrf @method('PUT')
        <section class="card animate-fade-in"><div class="border-b border-slate-200 p-5"><h3 class="text-base font-semibold text-slate-900">Purchase Order details</h3><p class="mt-0.5 text-sm text-slate-500">Line items remain linked to the approved source GE Order.</p></div><div class="grid grid-cols-1 gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3">
            <x-form-field name="po_number" label="PO Number" :value="old('po_number', $purchaseOrder->po_number)" :errors="$errors" required />
            <x-form-field name="order_date" label="Order Date" type="date" :value="old('order_date', $purchaseOrder->order_date->format('Y-m-d'))" :errors="$errors" required />
            <x-form-field name="expected_delivery_date" label="Expected Delivery" type="date" :value="old('expected_delivery_date', $purchaseOrder->expected_delivery_date?->format('Y-m-d'))" :errors="$errors" />
            <div><label for="status" class="block text-sm font-medium text-slate-700">Status <span class="text-rose-500">*</span></label><select id="status" name="status" class="input mt-1.5" required>@foreach (['draft' => 'Draft', 'ordered' => 'Ordered', 'backorder' => 'Backorder', 'partially received' => 'Partially Received', 'fully received' => 'Fully Received', 'cancelled' => 'Cancelled'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $purchaseOrder->status) === $value)>{{ $label }}</option>@endforeach</select>@error('status')<p class="mt-1 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror</div>
            <div><p class="text-sm font-medium text-slate-700">Supplier</p><p class="mt-1.5 rounded-lg bg-slate-50 px-3.5 py-2.5 text-sm text-slate-700">{{ $purchaseOrder->supplier->name }}</p></div><div><p class="text-sm font-medium text-slate-700">Source GE Order</p><a href="{{ route('ge-orders.show', $purchaseOrder->geOrder) }}" class="mt-2 inline-block font-mono text-sm font-semibold text-brand-600">{{ $purchaseOrder->geOrder->order_number }}</a></div>
            <div class="sm:col-span-2 lg:col-span-3"><x-form-field name="notes" label="Notes" type="textarea" :value="old('notes', $purchaseOrder->notes)" :errors="$errors" /></div>
        </div></section>
        <section class="card animate-fade-in mt-6"><div class="border-b border-slate-200 p-5"><h3 class="text-base font-semibold text-slate-900">Line items</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Item</th><th>Unit</th><th class="text-right">Quantity</th><th class="text-right">Unit Price</th><th class="text-right">Total</th></tr></thead><tbody>@foreach ($purchaseOrder->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->unit ?? '—' }}</td><td class="text-right tabular-nums">{{ $item->quantity }}</td><td class="text-right tabular-nums">K {{ number_format((float) $item->unit_price, 2) }}</td><td class="text-right font-medium tabular-nums">K {{ number_format((float) $item->total, 2) }}</td></tr>@endforeach</tbody></table></div></section>
        <div class="mt-6 flex justify-end gap-3"><a href="{{ route('procurement.show', $purchaseOrder) }}" class="btn btn-secondary">Cancel</a><button class="btn btn-primary"><i data-lucide="save" class="h-4 w-4"></i> Save Changes</button></div>
    </form>
</x-app-layout>
