<x-app-layout title="{{ $user->exists ? 'Edit User' : 'Add User' }}"><x-page-header :title="$user->exists ? 'Edit user' : 'Add user'" description="Set branch access and one supported system role." />
    <form method="POST" action="{{ $user->exists ? route('admin.users.update', $user) : route('admin.users.store') }}" class="card max-w-3xl p-6">@csrf @if($user->exists) @method('PUT') @endif<div class="grid gap-5 sm:grid-cols-2"><x-form-field name="name" label="Name" :value="old('name', $user->name)" :errors="$errors" placeholder="Full name" required /><x-form-field name="email" label="Email / login" type="email" :value="old('email', $user->email)" :errors="$errors" placeholder="name@example.com" required /><x-form-field name="branch_id" label="Branch" type="select" :errors="$errors">
                <option value="">No branch assigned</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)old('branch_id', $user->branch_id) === (string)$branch->id)>{{ $branch->name }}</option>@endforeach
            </x-form-field><x-form-field name="role" label="Role" type="select" :errors="$errors" required>@foreach($roles as $role)<option value="{{ $role }}" @selected(old('role', $user->getRoleNames()->first()) === $role)>{{ $role }}</option>@endforeach</x-form-field><x-form-field name="password" :label="$user->exists ? 'New password (optional)' : 'Password'" type="password" :errors="$errors" placeholder="At least 8 characters" :required="!$user->exists" /><x-form-field name="password_confirmation" label="Confirm password" type="password" :errors="$errors" placeholder="Re-enter the password" :required="!$user->exists" /><x-form-field name="is_active" label="Status" type="select" :errors="$errors" required>
                <option value="1" @selected(old('is_active', $user->is_active) == 1)>Active</option>
                <option value="0" @selected(old('is_active', $user->is_active) == 0)>Inactive</option>
            </x-form-field></div>
        <div class="mt-6 flex justify-end gap-3"><a href="{{ route('admin.users.index') }}" class="btn btn-secondary">Cancel</a><button class="btn btn-primary">Save user</button></div>
    </form>
</x-app-layout>